### ISSUE TITLE
ffmpeg takes long time to detect source

### ISSUE THREAD

**Issue by LostXine** [Allong12/py-scrcpy#3]
hi,
thank you for your work to bring scrcpy image into opencv framework. Especially scrcpy_client.py worked exactly what I expected.
However, every time when I started the script, it takes ffmpeg about 8-20 secs to detect source and output frames. I tried to set video decoder in ffmpeg's args but it changed nothing. 
I wonder if you got the same problem and what your solution was. Btw sometimes errors in P frame appeared which made me very confusing. Because original scrcpy client worked well (response fast and no error), the chance of a bad connection would be very little.
Any information would help, thanks.

I'm using Win10 with ffmpeg version N-93069-g6dc06e979c
Android device name is DLI-AL10

**Comment by LostXine** [comment]
Hi,
I've solved the problem by using Ctypes and FFmpeg DLLs. Now the stream is smooth with low latency. It also includes some origin FFmpeg features like precise image size, pts, dts and so on. Although my code can't cover all the functions that origin client has and only tested on Win10, it works well for my purpose. 
I'd like to thank you for hard-working and close this issue. Pull request is possible if you are interested.

**Comment by M6D6M6A** [comment]
Same Problem, and dont get how you solved it :/

**Comment by LostXine** [comment]
@Greansilver 
It would be very straight if you were familiar with FFmpeg. Just do what you usually did again in python rather than C. However if you need further information, please let me know and i will share a demo in 2-3 days.

**Comment by LostXine** [comment]
hi @Greansilver 
I've uploaded a demo [naive-scrcpy-client](https://github.com/LostXine/naive-scrcpy-client). You can have a try.
Good luck.
